### PR TITLE
Added flag checks to node-type-emitter so it can be pased to _onEmitD…

### PR DESCRIPTION
**Pull request by harangue**
…one.

Since `nextWhenReady()` is called multiple times for each directory, we only look for one NO_DESCEND flag with the ``flagSet`` variable.

### CODE REVIEW

**Comment by coolaj86** [comment]
git push --force to the max

YOLO!

THERE WILL BE NO SURVIVORS!!!

**Comment by harangue** [comment]
Haha did you even look at the code?

**Comment by coolaj86** [comment]
Yes, I did. It made sense once I looked at my related commit as well.

**Comment by coolaj86** [comment]
Looked pretty harmless. If I'm wrong I'll hear about it and then people will hate me and I'll know it was a bad choice.

**Comment by harangue** [comment]
What you don't know is that I sneaked an executable in the pull request and hacked GitHub so that it wouldn't appear. I have access to all your machines now, so kudos.

Seriously though, glad it (may) have helped!

**Pull request merged**
